# .streamlit/secrets.toml

[singlestore]
host = "svc-eaf40150-08b6-4b71-add5-5e3f4c9886ef-dml.aws-oregon-3.svc.singlestore.com"
port = 3306
database = "Wine_Database"
user = "admin"
password = "wine_Vinter"
